### ISSUE TITLE
Removing Manual Block Order Configuration

### ISSUE THREAD

**Issue by DerMilchmann** [BioMotionLab/TUX#11]
When adding a Manual Block order Configuration, I do not see a way to delete previous Manual Block Orders, except for editing the DesignFile.asset by hand.

Also when removing a blocked variable which was used for a manual block order, no blocks are auto-generated at all until every element in the list is removed by hand.

If the issue needs further description, I can try to provide screenshots.

**Comment by AdamBebko** [comment]
I have significantly changed how these configurations work, it should me much easier to use them now, and this bug should no longer be an issue. Please give me any feedback with this new system, since few people are using it currently. Check out the new release, but make sure you read the warning on the release page.
