### ISSUE TITLE
Feature Request: Easily Reorder Output Csv Columns

### ISSUE THREAD

**Issue by A-Ivan** [BioMotionLab/TUX#48]
It would be great to have an easy and user friendly way to define what order the columns would be in the output csv/data file. For instance, the Design file could have a way to first create all my variables (as it currently has), without having to worry about order, and then dragging the created variables around to reorder them top to bottom (being the top most variable the first column and the bottom most variable the last column).

For instance say I have created the following variables:

2 Independent Variables: I.1 & I.2
2 Dependent Variables: D.1, D.2
2 Participant Variables: P.1, P.2, P.3

I would then like to organize the output data columns to be in the following order (Participant, Independent, Dependent, with reordering in them): P.1, P.3, P.2, I.1, I.2, D.2, D.1

I think this can currently be done using the Design File -> Advanced Settings Option and using a Pre-Generated Trial Table, but this isn't very practical as you have to type in the names of the columns, which can lead to errors and frustration. Being able to reorder the variables in the Design File by dragging them around would make things much easier.

This could be similar to how the variable values can currently be dragged (Unity 2020.3.15f2).

![image](https://user-images.githubusercontent.com/17125077/148656546-f697dbbe-5c99-45c8-8263-e96d7e1d72b5.png)

**Comment by AdamBebko** [comment]
I think this is a low priority issue since people can do that pretty easy themselves, or using excel and other spreadsheet tools. I'm going to reprioritize this for now. Reorderable UI is becoming much easier in new unity versions (mostly built in now) but since bmlTUX supports older unity versions, and was build on these old versions I had to write all that reorder able logic myself, which was not easy to say the least. 

Going to close this issue for now. If you feel like attacking this in a pull request, let me know your plans and we can discuss it. But I think since my time is limited I'm going to shelve this for now.
