### ISSUE TITLE
How to define a practice block

### ISSUE THREAD

**Issue by Tomaso-Zanardi** [BioMotionLab/TUX#74]
Hi,

I wanted to ask you what would be the most straightforward way to set a practice block or multiple practice blocks for my experiment.
It seems to me that once an independent variable is set to be a block variable, blocks then contain the same number of trials.
What I would like to achieve is to have two initial short blocks of 5 trial each, and then an experimental block of 200 trials.

Thank you

**Comment by AdamBebko** [comment]
Hi Tomaso,

Unfortunately, there's no built-in solution for this since everyone has different needs.

You could write some custom stuff to handle that, I've done that before.

But the easiest way is to have two different scenes, with two different configs, using the exact same variables/script. So the only real difference is the trial table. The practice scene is loaded from a custom trial order file, and the "real scene" runs normally with counterbalancing/permutations etc.

You can just stop running, switch to the real scene and start running again after training is over. You can also write a script to handle the switch automatically, but that is more work.

Hope that gets you started
